import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/header'
import Footer from '../components/footer'
import Hero from '../components/hero'
import Card from '../components/card'
import Skills from '../components/skills'
import drupalLogo from '../public/drupal-logo.svg'
import tsLogo from '../public/ts-logo.svg'

const Home: NextPage = () => {
  return (
    <div className='bg-main-color min-h-screen'>
      <Head>
        <title>Cataco</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className='container mx-auto px-4'>
        <Hero/>

        <div className='grid grid-cols-3 gap-8 mt-20 mb-20'>
          <Card
            imgSrc={drupalLogo}
            title='Drupal'
            description='Maecenas sed diam eget risus varius blandit sit amet non magna. Etiam porta sem malesuada magna mollis euismod.'
            color='bg-blue-color'
          />
          <Card
            imgSrc={drupalLogo}
            title='React'
            description='Maecenas sed diam eget risus varius blandit sit amet non magna. Etiam porta sem malesuada magna mollis euismod.'
            color='bg-orange-color'
          />
          <Card
            imgSrc={tsLogo}
            title='TypeScript'
            description='Maecenas sed diam eget risus varius blandit sit amet non magna. Etiam porta sem malesuada magna mollis euismod.'
            color='bg-char-color'
          />
        </div>

        <h2 className='text-3xl font-bold mb-6'>I have experience in...</h2>
        <div className='grid grid-cols-8 gap-4'>
          <Skills skill='Drupal CMS' link='http://google.es'/>
          <Skills skill='React' link='http://google.es'/>
          <Skills skill='TypeScript' link='http://google.es'/>
          <Skills skill='Vue' link='http://google.es'/>
          <Skills skill='Jira' link='http://google.es'/>
          <Skills skill='Git' link='http://google.es'/>
          <Skills skill='Scrum' link='http://google.es'/>
          <Skills skill='JavaScript ES6' link='http://google.es'/>
          <Skills skill='jQuery' link='http://google.es'/>
          <Skills skill='Tailwind CSS' link='http://google.es'/>
          <Skills skill='SASS' link='http://google.es'/>
          <Skills skill='PostCSS' link='http://google.es'/>
          <Skills skill='Twig' link='http://google.es'/>
        </div>
      </main>

      <Footer />
    </div>
  )
}

export default Home
